### ISSUE TITLE
Add ability to specify path of generated files

### ISSUE THREAD

**Issue by coderberry** [hopsoft/containers#2]
For example:

```
containers generate compose --path="./.docker"
containers generate dockerfile --path="./.docker"
```

This would generate the docker-compose.yml and Dockerfile in the path ./.docker

**Comment by hopsoft** [comment]
This is a great idea and will provide a lot of flexibility.

**Comment by hopsoft** [comment]
I started implementing this but realized that the complexity probably isn't worth it. For example, if we support a `directory` option for generators, we'd need to support this option for every command. A better solution is to have users create the directory they want then `cd` to that directory and run `containers` commands there.

```sh
mkdir .example
cd .example
containers generate dockerfile
containers list
containers ...
cd .. # finished
```

I think we could also address targeting a `directory` for all commands with a `.containersrc` file as noted in #3.
